name: weather_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^4.0.3
  geolocator: ^14.0.2
  http: ^1.6.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/background/
